# Generated by Django 4.2.25 on 2025-10-20 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_menuitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
